vich_uploader:
    db_driver: orm

    mappings:
        profile:
            uri_prefix: /upload/foodhero
            upload_destination: '%kernel.project_dir%/public/upload/foodhero'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        offer:
            uri_prefix: /upload/offer
            upload_destination: '%kernel.project_dir%/public/upload/offer'
            namer: Vich\UploaderBundle\Naming\UniqidNamer